server:
  port: 6011
  context-path:
  profiles:
    active:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dynamicTest1?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver