server:
  port: 6002
  context-path:
  profiles:
    active:
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 2s